# Imagem base leve e estável
FROM python:3.11-slim

# Evita arquivos .pyc e força logs imediatos
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Diretório de trabalho dentro do container
WORKDIR /app

# Copia apenas o requirements primeiro (cache eficiente)
COPY requirements.txt .

# Instala dependências
RUN pip install --no-cache-dir -r requirements.txt

# Copia o restante do código
COPY . .

# Porta padrão do Flask
EXPOSE 5000

# Comando para rodar a aplicação
CMD ["python", "run.py"]
